### ISSUE TITLE
[Cancelled] Generate RSM-014/RSM-019 messages for BRS-023 and BRS-027 (MDR+DDM)

### ISSUE THREAD

**Issue by MadsBloendAndersen** [Energinet-DataHub/geh-aggregations#242]
### Description
Whenever a BRS-023 or BRS-027 process has succeeded, we forward the results to the relevant market parties.
_________________________________________________________________
BRS-023 processes triggers a RSM-014 CIM XML message to the market actors. Specific market actors must receive certain information, which is outlined here: 

**Grid company (MDR):** 
- Net exchange per grid area
- Production per grid
- Hourly consumption per grid
- Flex consumption per grid
- Total consumption (Hourly production per grid area + net exchange per grid area)

______________________________________________________________

BRS-027 processes triggers a RSM-014 & RSM-019 CIM XML message to the market actors. The results of the calculation are forwarded to charge owner, grid operator and energy suppliers per grid area as recipients. 

**Charge owner (Grid company (DDM))**
- Energy quantity per charge per supplier per charge owner per grid area per metering point type per settlement method (Only applicable for tariffs)
- Number of charge links per supplier per charge owner per grid area per metering point type per settlement method (Only applicable for subscriptions and fees)
- Prices per charge 
- Amounts per charge per supplier per charge owner per grid area metering point type per settlement method

Information about how subpostoffice and postoffice communicate can be found [here](https://github.com/Energinet-DataHub/geh-post-office)

Unique key collection (result message versioning):
- from date
- to date
- process type
- process variant
- simulation should not count
- grid area

Unique receiver of a message is identified by using `GLN`/`EIC` + `Role` eg. xxxx + DDK

**_SME's_**
- Khatozen (KWQ)
- Irene (IRS)
- Christian (CCO)

### Acceptance Criteria

- [ ] The messages with results from BRS-023 & BRS-027 are generated to the grid company. 
- [ ] Map results to CIM XML message to store in subpostoffice
- [ ] Inform postoffice that result message has been stored in subpostoffice
- [ ] Result messages should contain a version number following the description about version above
- [ ] If the charge is a Tax then information regarding this charge is send to DDM (Grid operator - not the charge owner)

### Developer notes
- RSM-019 can be used as an RSM-014 excluding charges related nodes (price, amount)

### Estimate
0,5 PI

**Comment by MadsBloendAndersen** [comment]
@mogensjuul I have changed this feature to focus only on sending messages to grid operator/company, from the aggregation domain.
