### ISSUE TITLE
[Enabler] Integration to other domains

### ISSUE THREAD

**Issue by MadsBloendAndersen** [Energinet-DataHub/geh-aggregations#252]
### Description
The aggregation domain needs data from almost all other domains, and needs to contain the current truth at all times. 

The following data is needed from the each domain: 

**Metering Point domain** (batman)
- MeteringPointID
- MeteringPointType
- SettlementMethod
- GridArea
- ConnectionState
- Resolution
- InGridArea
- OutGridArea
- ParentMeteringPointID (Cannot be delivered at the moment - Concept is under refinement)
- Unit 
- Product
- FromDate
- ToDate

**Charge Domain** (Volt)

_Charge master data_
- ChargeCode
- ChargeType
- ChargeOwner
- Resolution
- ChargeTax
- Currency
- Start
- End

_Charge prices_  (Volt)
- ChargePrice
- Time
- ChargeKey 

_Charge Links_ (Volt)
- ChargeKey
- MeteringPointID 
- Quantity of links
- Start
- End

**Timeseries domain** (Volt)
- MeteringPointID
- Quantity
- Quality
- Time

**Market roles** (Market roles)
- CurrentEnerySupplier
- MeteringPointID
- Start
- End

### Acceptance Criteria

- [x] The following data mentioned are available from the Metering point domain and stored in the aggregation domain. (**CreateMeteringPoint event** - all metering point types) 
- [ ] The following data mentioned are available from the Market roles domain and stored in the aggregation domain. (**CurrentEnergySupplier** event)
- [ ] The following data mentioned are available from the Charge domain and stored in the aggregation domain. (**CreateCharge**, **CreateChargeLink**, **CreateChargePrice event**)
- [ ] The following data mentioned are available from the Time series domain and stored in the aggregation domain. 
- [x] Aggregation domain can maintain metering point status from "New" to "Connected" (**ConnectMeteringPoint event**) 
- [ ] Aggregation domain are able to send timeseries on system correction and grid loss back to time series domain
- [x] Joules will provide test data in form of an excel sheet to import to the test environment.

### Estimate

0,5 PI - forudsat at protobuf, python & databricks er afklaret.

**Comment by MadsBloendAndersen** [comment]
Note: regarding service bus communication, reach out to Bjarke or Michael from volt or Kristian from batman.
