### ISSUE TITLE
[Enabler] Master data integration to other domains V2

### ISSUE THREAD

**Issue by MadsBloendAndersen** [Energinet-DataHub/geh-aggregations#342]
## Problem Description

Whenever master data changes on metering points, charges or market roles, the aggregation domain needs to update these changes too. 

If master data is not updated according to what is being represented in the other domains, then the calculations will be wrong.

The following data must be updated in the aggregation domain when an update occurs in any of these domains.

**MeteringPoint domain**
- Metering Points created (Consumption, production, child MP's)
- SettlementMethod
- ConnectionState
- Resolution
- ParentMeteringPoint 

**MarketRoles domain**
- Energy Supplier changes on the metering point

**ChargeDomain**
- Charge created (Maybe already done)
- Charge updated (Master data)
- Charge stopped (Master data)
- Charge prices updates
- Charge links created (Maybe already done)
- Charge link stop 
- Charge link updated (number of charge links) ONLY APPLICABLE FOR FEES AND SUBSCRIPTIONS

### Benefit Hypothesis
When the aggregation domain can consume data from other domains and maintain changes in data, we can run aggregation and wholesale settlements as the market expect us to.

## Acceptance criteria and must have scope
- [ ] The aggregation domain are can handle changes in master data on metering point level. This includes changes to settlement method, connection state, resolution & ParentMeteringPoint ID. 

- [ ] The aggregation domain can handle changes in master data on charges according to changes in charge domain. This includes charge creation and discontinuation.

- [ ] The aggregation domain can update charge prices according to change in charge domain.

- [ ] The aggregation domain are can handle changes in charge links created, stopped and updated.

- [ ] Given a business process is triggered that changes the energy supplier on a metering point (BRS-001 or BRS-009), When reaching the effective date of that event, Then aggregation domain is updated accordingly.

## Stakeholders
- Volt
- Batman 
- Khatozen
- Irene

## Timeline
What's the timeline for this feature, what resources are needed, and what might potentially block this from hitting the projected end date.

**Comment by MadsBloendAndersen** [comment]
Hi@mogensjuul. I have created this feature, that contains the rest of the integrations events the aggregation domain needs, and then kept what we are working on this PI6 on #252. this is mainly created events from metering points, market roles, and charges.

**Comment by mogensjuul** [comment]
@mnd tale om med MSP

**Comment by mknic** [comment]
@MadsBloendAndersen i would suggest that we split this feature into multiple features to be able to close a feature when integrations to a specific event have been completed.

**Comment by MadsBloendAndersen** [comment]
@mknic Let's discuss on Monday what would be a good way to split it. You are welcome to prepare some thoughts.

**Comment by MadsBloendAndersen** [comment]
@PerTHenriksen FYI
