### ISSUE TITLE
[Cancelled by wholesale feature] Enable datahub operations to verify calculations jobs

### ISSUE THREAD

**Issue by MadsBloendAndersen** [Energinet-DataHub/geh-aggregations#420]
## Synopsis
As PO/SME/Datahub operations, i want to manually trigger a calculations process and view results
So I can verify the aggregation and balance fixing process and support incident mangement  

## Acceptance criteria
AC1 (TriggerProcess)
- [ ] Given PO/SME/Datahub operations, when triggering a calculation job, Then the following input is required;
_- ProcessType (Aggregation/Balance fixing)_ 
_- JobType (Market run/Simulation)_ 
_- Period (StartDate & EndDate)_
_- GridArea(s) (Empty list implies all grid areas)_

AC2 (JobStatus)
- [ ] Given a calculation job, When triggered, Then it must be possible to get job description which includes; 
_- JobID_
_- ProcessType_ 
_- JobOwner_ 
_- JobStartTime_
_- JobEndTime_
_- GridArea_
_- JobExecutionStartTime_
_- JobExecutionEndTime_
and se current JobStatus;
_- Scheduled_
_- Running_
_- Completed_ 
_- Error_

AC3 (ViewResults)
- [ ] Given a calculation job, When completed, Then datahub operation/PO/SME is able to view all results for a specific job. 

Define necessary mockup's

**Comment by MadsBloendAndersen** [comment]
@BjarkeMeier + @khatozen will you take a look at this?

**Comment by MadsBloendAndersen** [comment]
@mknic her er den feature jeg snakkede om her den anden dag. Den hvor der vil komme noget UX arbejde.
