### ISSUE TITLE
[being closed, to be replaced by #746] Time series from meter data responsible are included in calculations jobs

### ISSUE THREAD

**Issue by MadsBloendAndersen** [Energinet-DataHub/geh-aggregations#471]
## Problem Description
Timeseries are core data for the aggregation domain.

In this feature, a solution of how to publish timeseries to aggregation domain must be designed and implemented, so whenever time-series enter the time-series domain, these will be used in a calculation job. 

The following flow must be supported, when this feature is finished 
![image](https://user-images.githubusercontent.com/72008712/152175831-631dbb73-ddac-40ac-bddc-6656b8941f1d.png)

### Benefit Hypothesis
Timeseries are the value to the aggregation and wholesale jobs. Without them we could not perform settlement. 

## Acceptance criteria and must have scope

- [ ] Given a meter data responsible submits a CIM-based RSM-012, when datahub completes an aggregation (D03) process, Then RSM-014 is available for the meter data responsible, through message hub.
- [ ] Given an aggregation process has completed, When examining the generated RSM-014, Then energy sums per grid area is available in the message.
- [ ] The design must support future performance requirements which is 2,5 mil timeseries/hour of 24/96 positions each
- [ ] Given metering points has status connected, when triggering a job, then they are included
- [ ] Given multiple time series are submitted for the same period for the same metering point, Then the most recent time series is used in aggregation job. 
- [ ] The described flow is working on B-002.
- [x] We should be able to receive bundled timeseries messages.

_Out of scope_
- Business validation on timeseries
- Integration events from metering point to timeseries domain
- Balance fixing process and locking of periods

Tech note: 
- [ ] Triggering of process is done through postman or related tool

1. We need to be able to get notified if a streaming job is running or is stopped. (surveailance) health / ops
    - What to do if streaming job fails and stops?
        - *[Retry logic](https://docs.databricks.com/spark/latest/structured-streaming/production.html) is applicable for streaming jobs - LKI 25-01-2022*
    - What happens to the received time series that is added to event hub?
        - *The events on the event hub should still be available on event hub until consumed by streaming job with a retention of up to seven days if standard tier is selected for event hub, [reference link](https://docs.microsoft.com/en-us/azure/event-hubs/event-hubs-capture-overview). - LKI 25-01-2022*
        - *Another option to allow for almost indefinite event retention is to use Azure Event Hubs Capture ([link<sup>1</sup>](https://docs.microsoft.com/en-us/azure/event-hubs/event-hubs-capture-enable-through-portal), [link<sup>2</sup>](https://github.com/Azure-Samples/streaming-at-scale/tree/main/eventhubs-capture-databricks-delta)), which essentially consumes events from Event Hub and stores them in a storage account or data lake in avro format. - LKI 25-01-2022*
        - *If opting for Azure Event Hubs Capture, an option is to use [Databricks Auto Loader](https://docs.microsoft.com/en-us/azure/databricks/spark/latest/structured-streaming/auto-loader) to stream events from data lake into delta lake on new files detected. This can be done using [Avro as file format](https://docs.microsoft.com/en-us/azure/databricks/spark/latest/structured-streaming/auto-loader-avro). Read more on how to [configure Auto Loader](https://docs.microsoft.com/en-us/azure/databricks/spark/latest/structured-streaming/auto-loader-gen2). - LKI 25-01-2022*
    - How can we restart the streaming job and receive the queued up time series on the event hub?
        - *It is possible to specify a [checkpoint location](https://docs.databricks.com/spark/latest/structured-streaming/production.html) for a streaming job, which holds information on which events have been processed. - LKI 25-01-2022*
2. Performance tests to document how much data we can handle. (needs metrics defined)

## Non Functional Requirements

- [ ] All inbound and outbound messages are logged
- [ ] Developers and business are confident that the described flow can work in actor test.

## Stakeholders
Khatozen
Irene
Volt

### Note: 
- ~~Actor register / Authorization~~ (Not in scope)
- Performance (The design must support future performance requirements which is 2,5 mil/hour of 24/96 positions each)
- expected input/output (initial small data sets)
- expected integrations (Aggregation domain -> metering points domain)
- expected mock data (Aggregation domain -> market roles + charges) (Timeseries domain -> metering point + market roles)
- Domain test
- Metering point validations 
- process triggering
- retry logic
- disaster recovery
- monitoring
- schema evolution
- Eventual consistency
- Time series  deployment
- Post office integration
- Scaling

**Comment by mogensjuul** [comment]
@msp Tjek

**Comment by MadsBloendAndersen** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Feature-board-60e2eb437d96850014aa15ab/issues/Energinet-DataHub/geh-aggregations/471?planning-poker) with ZenHub @ZavezX @BjarkeMeier @HenrikSommer

**Comment by MadsBloendAndersen** [comment]
@BjarkeMeier @ZavezX @HenrikSommer estimate in "man sprint" :)
