### ISSUE TITLE
New metering points and master data updates are included in the aggregation job

### ISSUE THREAD

**Issue by MadsBloendAndersen** [Energinet-DataHub/geh-aggregations#485]
## Problem Description
The aggregation domain needs a current representation of metering point master data. 
This includes (1) All new created metering points (2) updates to settlement method, connection state, resolution & parent metering point ID. 

All master data on metering points mentioned in this feature is included in the snapshot for a calculations job. When a calculation job has finished a CIM based RSM-014 is generated and reported ready for shipping, through post office. 

While metering point master data might be the only real data from all other domain, we will fill in the blanks, with mock data. 

### Benefit Hypothesis
We need a current representation of all metering points in the aggregation domain so we can perform calculations jobs with current master data. 

## Acceptance criteria and must have scope
- [ ] Given a RSM-021/E02  is forwarded to Datahub, When creating a new metering point (E17, E18, E20), Then the same metering point is created in the aggregation domain.

~~- [ ] Given a RSM-021/E32  is forwarded to Datahub, When updating SettlementMethod, Resolution, or ParentMPID, Then this update is reflected aggregation domain.~~
~~- [ ] Given a RSM-021/E79  is forwarded to datahub, When the connection state on a metering point is either changed to connected or disconnected, Then this change is reflected in the aggregation domain.~~
~~- [ ] Given a RSM-021/D14  is forwarded to datahub, When a metering point is closed down at effective date X, Then "ToDate" on that metering point is equal to effective date X in the aggregation domain.~~

- [ ] Given AC1-2 is completed, When triggering an aggregation process for period X, data from the metering point domain is used in the calculations
- [ ] Given a calculation job Is triggered, When the job is complete, Then and RSM-014 (MDR) is generated and reported ready for "shipping"  

## Stakeholders
Batman
CCO
JTI
KWQ
Titans
Mighty Ducks
