### ISSUE TITLE
Ensure correct behaviour and efficient development of the time series domain

### ISSUE THREAD

**Issue by MadsBloendAndersen** [Energinet-DataHub/geh-aggregations#578]
### Description

As DataHub
I want the time series domain to be sufficiently automated tested
So that I can be confident about the quality of releases

As a developer
I want the necessary automated tests types and tools
So that I can be efficient and confident that new and existing code works as intended with fast feedback

scope?
scenarios?

### Acceptance criteria

- [ ] Integration test can be executed both locally and in pipeline
- [ ] Given the suite of automated tests When any test fails Then the PR gate rejects the pull-request
- [ ] We have high confidence in quality based on the developed automated test suite.

### Tech notes

- https://towardsdatascience.com/elegant-cicd-with-databricks-notebooks-760623bb3e9b
- https://medium.com/@paulomiguelbarbosa/mlops-project-template-integrating-github-with-databricks-docker-and-spark-cca871e1e8e6
- https://github.com/marketplace/actions/databrick-notebook-run
