### ISSUE TITLE
Created metering points are ready for aggregation

### ISSUE THREAD

**Issue by MadsBloendAndersen** [Energinet-DataHub/geh-aggregations#616]
@MadsBloendAndersen commented on [Wed Feb 23 2022](https://github.com/Energinet-DataHub/geh-metering-point/issues/757)

### Synopsis
As datahub
I want to keep track of all created metering points
so that i can prepare to use them in an aggregation

### Acceptance criteria
AC1
- [ ] Given grid company, When creating a new metering point, Then related metering point master data are stored, ready for calculation jobs.

AC2 
- [ ] The following metering point master data is needed in calculations jobs and therefore must be available in aggregation domain.

- MeteringPointID
- MeteringPointType
- SettlementMethod
- GridArea
- ConnectionState
- Resolution
- InGridArea
- OutGridArea
- MeteringMethod
- NetSettlementGroup
- ParentMeteringPointID
- Unit
- Product
- EffectiveDate 

AC3:
- [x] Idempotency

### Tech notes
- [x] Generate metering point data in metering point domain (Postman)  
- [x] Receive metering point created integration event in azure function
- [x] Convert metering point master data to internal object
- [x] Publish to internal eventhub 
- [x] Receive internal event in streaming job
- [x] Store new metering points in delta lake, ready for a calculation job.

### Task list
- [x] Create unit test to validate idempotency
- [x] Create service inside IntegrationEventListener that takes events and transforms into master data @kristianschneider 
- [x] Convert python unit tests to .NET @kristianschneider 
- [x] Create database for master data with terraform
- [x] Create migration scripts for master data tables
- [x] Set database connection string in terraform to be used by IntegrationEventListener
- [x] Refactor prepare job to load master data from sql database - @BjarkeMeier 
- [x] Refactor integration test in IntegrationEventListener
- [x] Publish historical time-series observations
- [x] Rename "processed_timeseries" according to architecture drawings (and agree with PO on name for points)
- [x] Clean up the old streaming job (infra, python code, dh3environments etc) @johevemi and @kristianschneider 
- [x] Add Health check for integration-event-listner fuction endpoint @kristianschneider 
- [x] Integration test integration-event-listener @kristianschneider  
- [x] Unit test "latest time series points" @johevemi 
- [x] Integration test prepare job @BjarkeMeier and Sebastian
- [x] PR gate must require pytest testsuite to succeed @johevemi 
- [x] Publish registration data time with fallback from time series domain and use in aggregations. Please make the contract between the domain more explicit. @johevemi 
- [x] Improve python intellisense in container [using jedi](https://stackoverflow.com/questions/62558683/autocomplete-python-in-vscode-remote-container)
- [x] Load grid-loss-sys-corr from SQL - not from Delta table @BjarkeMeier 
- [x] Prepare EF Core implementation @ZavezX  @lasrinnil

**Comment by MadsBloendAndersen** [comment]
@ZavezX + @kristianschneider jeg har prøvet at skrive lidt mere på de stories jeg har oprettet.

**Comment by lasrinnil** [comment]
We got a health check for the event-integration-listener !

![image.png](https://images.zenhubusercontent.com/60bdfcb3effb2082025638c1/6141bf52-cbc6-4ad8-a377-e279afd08efd)

**Comment by BjarkeMeier** [comment]
Nice @lasrinnil  - does it send reports to the DevOps channels on failure?
