### ISSUE TITLE
Enable FAS user to order basis data of an balance fixing in CSV

### ISSUE THREAD

**Issue by PerLysemose** [Energinet-DataHub/geh-aggregations#750]
## Problem Description
As a user
I want to view basis data of a balance fixing process in CSV format
So that PO/SME can verify that balance fixing results corresponds to the given input data and verify the expected input with the actual input.

## Acceptance criteria and must have scope
- [ ] When starting a balance fixing process, then time series - and metering point basis data is available to be ordered
- [ ] Enable PO/SME to order time series and metering point master data through GUI search batch screen
- [ ] Add new column called "Basis data" in search batch GUI screen 
- [ ] For each row, add an option/button called "Download" 
- [ ] When pushing the download button for a specific process, a ZIP-file is downloaded containing time series and metering point basis data

![image.png](https://images.zenhubusercontent.com/60d0699cbe9e2f6f18493e89/8e1ad184-9384-4f28-8279-ce284ea111b6)

**Comment by MadsBloendAndersen** [comment]
@khatozen do you agree that this feature can be closed
