### ISSUE TITLE
Time series basis data for a balance fixing process is available

### ISSUE THREAD

**Issue by MadsBloendAndersen** [Energinet-DataHub/geh-aggregations#875]
## Description 
As a user
i want to prepare time series basis data for a specific process
so that I can compare the expected input to the process with the actual output

## Acceptance criteria
- [ ]  Timeseries basis data are available when a balance fixing process are completed.

- [ ] Each row in the time series report is distinguished by the following attributes:
![image.png](https://images.zenhubusercontent.com/6110f1589f04be24392a986f/55ab5ce0-b2d4-4516-a147-6e162cefb2ad)

An example of the report for hourly time series:
METERINGPOINTID,TYPEOFMP,STARTDATETIME,ENERGYQUANTITY1,ENERGYQUANTITY2, ENERGYQUANTITY3,ENERGYQUANTITY4,ENERGYQUANTITY5,………………,ENERGYQUANTITY25
570667000000000999,E17,2022-08-31T22:00:00Z,1.0,1.3,4.1,2.1,4.4,……,1.2, 
570667000000000999,E17,2022-09-01T22:00:00Z,1.0,1.3,4.1,2.1,4.4,……,1.2,

An example of the report for quarterly time series:
METERINGPOINTID,TYPEOFMP,STARTDATETIME,ENERGYQUANTITY1,ENERGYQUANTITY2, ENERGYQUANTITY3,ENERGYQUANTITY4,ENERGYQUANTITY5,………………,ENERGYQUANTITY100
5706670000000007885,E17,2022-08-31T22:00:00Z,1.0,1.3,4.1,2.1,4.4,…………………………,1.2, 
5706670000000007885,E17,2022-09-01T22:00:00Z,1.0,1.3,4.1,2.1,4.4,……………………………,1.2,

Note that the exact number of quantity columns depends on daylight savings.

## Tasks
- [x] Refactor spark integration tests to fast tests
- [x] Fix todos

**Comment by khatozen** [comment]
@BjarkeMeier: Vi skal have to filer for basis data, en for timeværdier og en for kvartersværdier.
Vi må ikke konverter timeværdier til kvartersværdier og levere kun en fil.

**Comment by BjarkeMeier** [comment]
@MadsBloendAndersen , @khatozen , do you want to keep the resolution duration columns? They are already implied by the file.

**Comment by MadsBloendAndersen** [comment]
@BjarkeMeier  Not sure what you mean by "resolution duration columns". Do ou mean the column header name for each point?

**Comment by lasrinnil** [comment]
@MadsBloendAndersen  @khatozen when you want to test this story, please reach out to me with the "Batch-nummer" of the process you started, ill get you the .csv files for you to inspect.

**Comment by MadsBloendAndersen** [comment]
@lasrinnil Hi Lasse. 
I can see in the CSV file , when i convert it to XLSX, then thousands must be separated with a "," 
See screenshot:
![image.png](https://images.zenhubusercontent.com/60d0699cbe9e2f6f18493e89/517d2f14-3b0a-4089-863c-105fdc294907)

**Comment by MadsBloendAndersen** [comment]
@khatozen what do you say? the CSV looks like this: 
![image.png](https://images.zenhubusercontent.com/60d0699cbe9e2f6f18493e89/5c4f5655-cf84-4611-b494-330f51a388fc)

Which actually looks like the CSV file we get from DH2. So I don't know, why excel won't convert separating thousands.

**Comment by MadsBloendAndersen** [comment]
@lasrinnil I have tested the following issue.
Found no issues. looks good. 

 [https://app.zenhub.com/files/345472293/f7dacf90-afe7-4f44-ba5f-793a1112b6a1/download](https://app.zenhub.com/files/345472293/f7dacf90-afe7-4f44-ba5f-793a1112b6a1/download)
